// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/grupokindynos/tyche/services (interfaces: HestiaService,PlutusService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	hestia "github.com/grupokindynos/common/hestia"
	plutus "github.com/grupokindynos/common/plutus"
	reflect "reflect"
)

// MockHestiaService is a mock of HestiaService interface
type MockHestiaService struct {
	ctrl     *gomock.Controller
	recorder *MockHestiaServiceMockRecorder
}

// MockHestiaServiceMockRecorder is the mock recorder for MockHestiaService
type MockHestiaServiceMockRecorder struct {
	mock *MockHestiaService
}

// NewMockHestiaService creates a new mock instance
func NewMockHestiaService(ctrl *gomock.Controller) *MockHestiaService {
	mock := &MockHestiaService{ctrl: ctrl}
	mock.recorder = &MockHestiaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHestiaService) EXPECT() *MockHestiaServiceMockRecorder {
	return m.recorder
}

// GetCoinsConfig mocks base method
func (m *MockHestiaService) GetCoinsConfig() ([]hestia.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinsConfig")
	ret0, _ := ret[0].([]hestia.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinsConfig indicates an expected call of GetCoinsConfig
func (mr *MockHestiaServiceMockRecorder) GetCoinsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinsConfig", reflect.TypeOf((*MockHestiaService)(nil).GetCoinsConfig))
}

// GetShiftStatus mocks base method
func (m *MockHestiaService) GetShiftStatus() (hestia.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftStatus")
	ret0, _ := ret[0].(hestia.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftStatus indicates an expected call of GetShiftStatus
func (mr *MockHestiaServiceMockRecorder) GetShiftStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftStatus", reflect.TypeOf((*MockHestiaService)(nil).GetShiftStatus))
}

// UpdateShift mocks base method
func (m *MockHestiaService) UpdateShift(arg0 hestia.Shift) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShift", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShift indicates an expected call of UpdateShift
func (mr *MockHestiaServiceMockRecorder) UpdateShift(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShift", reflect.TypeOf((*MockHestiaService)(nil).UpdateShift), arg0)
}

// MockPlutusService is a mock of PlutusService interface
type MockPlutusService struct {
	ctrl     *gomock.Controller
	recorder *MockPlutusServiceMockRecorder
}

// MockPlutusServiceMockRecorder is the mock recorder for MockPlutusService
type MockPlutusServiceMockRecorder struct {
	mock *MockPlutusService
}

// NewMockPlutusService creates a new mock instance
func NewMockPlutusService(ctrl *gomock.Controller) *MockPlutusService {
	mock := &MockPlutusService{ctrl: ctrl}
	mock.recorder = &MockPlutusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPlutusService) EXPECT() *MockPlutusServiceMockRecorder {
	return m.recorder
}

// DecodeRawTx mocks base method
func (m *MockPlutusService) DecodeRawTx(arg0, arg1 string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeRawTx", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeRawTx indicates an expected call of DecodeRawTx
func (mr *MockPlutusServiceMockRecorder) DecodeRawTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeRawTx", reflect.TypeOf((*MockPlutusService)(nil).DecodeRawTx), arg0, arg1)
}

// GetNewPaymentAddress mocks base method
func (m *MockPlutusService) GetNewPaymentAddress(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewPaymentAddress", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewPaymentAddress indicates an expected call of GetNewPaymentAddress
func (mr *MockPlutusServiceMockRecorder) GetNewPaymentAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewPaymentAddress", reflect.TypeOf((*MockPlutusService)(nil).GetNewPaymentAddress), arg0)
}

// GetWalletBalance mocks base method
func (m *MockPlutusService) GetWalletBalance(arg0 string) (plutus.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletBalance", arg0)
	ret0, _ := ret[0].(plutus.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletBalance indicates an expected call of GetWalletBalance
func (mr *MockPlutusServiceMockRecorder) GetWalletBalance(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletBalance", reflect.TypeOf((*MockPlutusService)(nil).GetWalletBalance), arg0)
}

// SubmitPayment mocks base method
func (m *MockPlutusService) SubmitPayment(arg0 plutus.SendAddressBodyReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPayment", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitPayment indicates an expected call of SubmitPayment
func (mr *MockPlutusServiceMockRecorder) SubmitPayment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPayment", reflect.TypeOf((*MockPlutusService)(nil).SubmitPayment), arg0)
}
